//@ui5-bundle sap/ushell/components/runtimeSwitcher/Component-preload.js
sap.ui.require.preload({
	"sap/ushell/components/runtimeSwitcher/Component.js":function(){
// Copyright (c) 2009-2022 SAP SE, All Rights Reserved
sap.ui.define(["sap/ui/core/UIComponent"],function(e){"use strict";return e.extend("sap.ushell.components.runtimeSwitcher.Component",{metadata:{manifest:"json",library:"sap.ushell"}})});
},
	"sap/ushell/components/runtimeSwitcher/controller/RuntimeSwitcher.controller.js":function(){
//Copyright (c) 2009-2022 SAP SE, All Rights Reserved
sap.ui.define(["sap/ui/core/mvc/Controller","sap/ushell/components/pages/controller/PagesAndSpaceId"],function(e,t){"use strict";return e.extend("sap.ushell.components.runtimeSwitcher.controller.RuntimeSwitcher",{onInit:function(){this.oNavContainer=this.byId("switcherNavContainer");this.oPagesRuntime=this.byId("pagesRuntime");this.oWorkpageRuntime=this.byId("workpagesRuntime");return this._handleRouter().then(function(){var e=sap.ushell.Container.getRenderer();this.oContainerRouter=e.getRouter();this.oContainerRouter.getRoute("home").attachMatched(this._handleRouter,this);this.oContainerRouter.getRoute("openFLPPage").attachMatched(this._handleRouter,this)}.bind(this))},_handleRouter:function(){var e;return Promise.all([t._getPageAndSpaceId(),sap.ushell.Container.getServiceAsync("Menu")]).then(function(t){var o;e=t[0]&&t[0].pageId;if(!e){return Promise.reject("No pageId found")}o=t[1];return o.isWorkPage(e)}).then(function(e){if(e){this._toggleToWorkPagesRuntime()}else{this._toggleToPagesRuntime()}}.bind(this)).catch(function(){this._toggleToPagesRuntime()}.bind(this))},_toggleToPagesRuntime:function(){this.oNavContainer.to(this.oPagesRuntime);if(this.oWorkPageRuntimeComponent){this.oWorkPageRuntimeComponent.hideRuntime()}if(this.oPageRuntimeComponent){this.oPageRuntimeComponent.onRouteMatched()}},_toggleToWorkPagesRuntime:function(){this.oNavContainer.to(this.oWorkpageRuntime);if(this.oPageRuntimeComponent){this.oPageRuntimeComponent.hideRuntime()}if(this.oWorkPageRuntimeComponent){this.oWorkPageRuntimeComponent.onRouteMatched()}},onExit:function(){this.oContainerRouter.getRoute("home").detachRouteMatched(this._handleRouter,this);this.oContainerRouter.getRoute("openFLPPage").detachRouteMatched(this._handleRouter,this)},pageComponentCreated:function(e){this.oPageRuntimeComponent=e.getParameter("component")},workPageComponentCreated:function(e){this.oWorkPageRuntimeComponent=e.getParameter("component")}})});
},
	"sap/ushell/components/runtimeSwitcher/manifest.json":'{"_version":"1.39.0","sap.app":{"id":"sap.ushell.components.runtimeSwitcher","applicationVersion":{"version":"1.108.31"},"ach":"CA-FLP-FE-COR","type":"component","title":""},"sap.ui":{"technology":"UI5","deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"componentName":"sap.ushell.components.runtimeSwitcher","rootView":{"viewName":"sap.ushell.components.runtimeSwitcher.view.RuntimeSwitcher","type":"XML","async":true},"componentUsages":{"pagesComponent":{"name":"sap.ushell.components.pages","componentData":{"navigationDisabled":true},"lazy":true},"workpageComponent":{"name":"sap.ushell.components.workPageRuntime","componentData":{"navigationDisabled":true},"lazy":true}}}}',
	"sap/ushell/components/runtimeSwitcher/view/RuntimeSwitcher.view.xml":'<mvc:View\n    xmlns="sap.m"\n    xmlns:core="sap.ui.core"\n    xmlns:mvc="sap.ui.core.mvc"\n    controllerName="sap.ushell.components.runtimeSwitcher.controller.RuntimeSwitcher"\n    height="100%"><NavContainer id="switcherNavContainer"><Page\n            id="emptyPage"\n            showHeader="false" /><Page\n            id="pagesRuntime"\n            enableScrolling="false"\n            showHeader="false"><core:ComponentContainer\n                height="100%"\n                usage="pagesComponent"\n                manifest="true"\n                componentCreated=".pageComponentCreated"\n                async="true"/></Page><Page\n            id="workpagesRuntime"\n            enableScrolling="false"\n            showHeader="false"><core:ComponentContainer\n                height="100%"\n                usage="workpageComponent"\n                manifest="true"\n                componentCreated=".workPageComponentCreated"\n                async="true"/></Page></NavContainer></mvc:View>\n'
});
//# sourceMappingURL=Component-preload.js.map
